/* ═══════════════════════════════════════════════
   YOSSICO — Catálogo de Productos
   ═══════════════════════════════════════════════ */

const YOSSICO_PRODUCTS = {

    oslo: {
        id: 'oslo',
        name: 'OSLO',
        line: 'Essentials',
        sub: 'Set · Scrub Femenino · Top + Pantalón',
        price: 275900,
        priceDisplay: '$275.900 COP',
        tag: 'Essentials',
        desc: 'Inspirado en la serenidad escandinava, el Set OSLO combina líneas limpias y una paleta de colores sobria con una confección estructurada. Top con cuello V clásico, bolsillos funcionales a los lados y pantalón recto de corte femenino con elástico y cordón. Pensado para la profesional que valora el confort sin sacrificar la elegancia.',
        features: [
            { label: 'Composición', value: 'Tela técnica resinada · 80% poliéster, 20% viscosa' },
            { label: 'Corte', value: 'Slim fit femenino · talle entallado' },
            { label: 'Detalles top', value: 'Cuello V con vivo · dos bolsillos laterales · vivo en mangas' },
            { label: 'Pantalón', value: 'Bota recta · elástico + cordón en cintura · bolsillos laterales' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina frío · no usar secadora · plancha a baja temperatura' },
        ],
        colors: [
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/negro.png', 'img/negro.png', 'img/negro.png'] },
            { key: 'azul-oscuro', label: 'Azul Marino', hex: '#1a2744', imgs: ['img/azul-oscuro.png', 'img/azul-oscuro.png', 'img/azul-oscuro.png'] },
            { key: 'gris', label: 'Gris', hex: '#7a8084', imgs: ['img/gris.png', 'img/gris.png', 'img/gris.png'] },
            { key: 'azul-claro', label: 'Azul Acero', hex: '#4a6fa5', imgs: ['img/azul-claro.png', 'img/azul-claro.png', 'img/azul-claro.png'] },
        ],
        defaultImgs: ['img/oslo.png', 'img/oslo-2.png', 'img/oslo-3.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20OSLO%20de%20YOSSICO',
    },

    milan: {
        id: 'milan',
        name: 'MILAN',
        line: 'Signature',
        sub: 'Set · Scrub Femenino · Top + Pantalón',
        price: 339900,
        priceDisplay: '$339.900 COP',
        tag: 'Signature',
        desc: 'El Set MILAN captura la elegancia italiana con un top de cuello mao, corte entallado y pantalón recto de alta precisión. En navy profundo, proyecta autoridad y sofisticación en cada turno. La línea Signature eleva el uniforme a una declaración de identidad profesional.',
        features: [
            { label: 'Composición', value: 'Tela técnica premium · 85% poliéster, 15% elastano' },
            { label: 'Corte', value: 'Slim fit · corte entallado con mayor movilidad' },
            { label: 'Detalles top', value: 'Cuello mao · botones al tono · bolsillo pecho izquierdo con bordado' },
            { label: 'Pantalón', value: 'Bota recta · elástico + cordón · dos bolsillos laterales y uno trasero' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina frío · no usar secadora · plancha a baja temperatura' },
        ],
        colors: [
            { key: 'azul-oscuro', label: 'Navy', hex: '#1a2744', imgs: ['img/milan.png', 'img/milan-2.png', 'img/milan-3.png'] },
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/negro.png', 'img/negro.png', 'img/negro.png'] },
            { key: 'gris', label: 'Gris', hex: '#7a8084', imgs: ['img/gris.png', 'img/gris.png', 'img/gris.png'] },
            { key: 'azul-claro', label: 'Azul Acero', hex: '#4a6fa5', imgs: ['img/azul-claro.png', 'img/azul-claro.png', 'img/azul-claro.png'] },
        ],
        defaultImgs: ['img/milan.png', 'img/milan-2.png', 'img/milan-3.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20MILAN%20de%20YOSSICO',
    },

    kyoto: {
        id: 'kyoto',
        name: 'KYOTO',
        line: 'Signature',
        sub: 'Set · Scrub Femenino · Top + Pantalón',
        price: 339900,
        priceDisplay: '$339.900 COP',
        tag: 'Signature',
        desc: 'KYOTO encarna la filosofía zen japonesa: un top cruzado con cuello cruzado y pantalón palazzo de caída impecable. Para la profesional que busca fluidez, calma y presencia. La línea Signature está diseñada para quienes entienden que el detalle lo es todo.',
        features: [
            { label: 'Composición', value: 'Tela técnica premium · 85% poliéster, 15% elastano' },
            { label: 'Corte', value: 'Palazzo · pantalón ancho de caída fluida' },
            { label: 'Detalles top', value: 'Cuello cruzado · cierre oculto · bolsillos laterales profundos' },
            { label: 'Pantalón', value: 'Palazzo amplio · elástico en cintura · caída premium' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina frío · no usar secadora · plancha a baja temperatura' },
        ],
        colors: [
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/negro.png', 'img/negro.png', 'img/negro.png'] },
            { key: 'gris', label: 'Gris', hex: '#7a8084', imgs: ['img/gris.png', 'img/gris.png', 'img/gris.png'] },
            { key: 'azul-claro', label: 'Azul Acero', hex: '#4a6fa5', imgs: ['img/azul-claro.png', 'img/azul-claro.png', 'img/azul-claro.png'] },
        ],
        defaultImgs: ['img/kyoto.png', 'img/kyoto-2.png', 'img/kyoto-3.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20KYOTO%20de%20YOSSICO',
    },

    rio: {
        id: 'rio',
        name: 'RIO',
        line: 'Essentials',
        sub: 'Set · Scrub Femenino · Top + Pantalón',
        price: 275900,
        priceDisplay: '$275.900 COP',
        tag: 'Essentials',
        desc: 'RIO trae la energía vibrante latinoamericana al uniforme médico: top tipo V con bolsillos funcionales y pantalón jogger con cargo pocket lateral. Para la profesional que busca dinamismo y comodidad sin comprometer la presencia.',
        features: [
            { label: 'Composición', value: 'Tela técnica resinada · 80% poliéster, 20% viscosa' },
            { label: 'Corte', value: 'Relaxed fit · corte holgado pero estructurado' },
            { label: 'Detalles top', value: 'Cuello V · bolsillos laterales profundos · manga con detalle' },
            { label: 'Pantalón', value: 'Jogger · cargo pocket lateral · elástico + cordón en cintura · bota ajustada' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina frío · no usar secadora · plancha a baja temperatura' },
        ],
        colors: [
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/negro.png', 'img/negro.png', 'img/negro.png'] },
            { key: 'gris', label: 'Gris', hex: '#7a8084', imgs: ['img/gris.png', 'img/gris.png', 'img/gris.png'] },
            { key: 'azul-claro', label: 'Azul Acero', hex: '#4a6fa5', imgs: ['img/azul-claro.png', 'img/azul-claro.png', 'img/azul-claro.png'] },
        ],
        defaultImgs: ['img/rio.png', 'img/rio-2.png', 'img/rio-3.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20RIO%20de%20YOSSICO',
    },

    lima: {
        id: 'lima',
        name: 'LIMA',
        line: 'Essentials',
        sub: 'Set · Scrub Femenino · Top + Pantalón',
        price: 275900,
        priceDisplay: '$275.900 COP',
        tag: 'Essentials',
        desc: 'LIMA captura la calidez latinoamericana en un diseño atemporal. Top suelto con cuello V redondeado y pantalón palazzo de caída fluida, pensado para quienes buscan comodidad sin perder el estilo. Una prenda que acompaña desde el primer turno hasta el último.',
        features: [
            { label: 'Composición', value: 'Tela técnica resinada · 80% poliéster, 20% viscosa' },
            { label: 'Corte', value: 'Fit holgado · top suelto con pantalón de caída fluida' },
            { label: 'Detalles top', value: 'Cuello V redondeado · bolsillos laterales · dobladillo recto' },
            { label: 'Pantalón', value: 'Palazzo · elástico en cintura · amplitud total en bota' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina frío · no usar secadora · plancha a baja temperatura' },
        ],
        colors: [
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/negro.png', 'img/negro.png', 'img/negro.png'] },
            { key: 'gris', label: 'Gris', hex: '#7a8084', imgs: ['img/gris.png', 'img/gris.png', 'img/gris.png'] },
            { key: 'azul-claro', label: 'Azul Acero', hex: '#4a6fa5', imgs: ['img/azul-claro.png', 'img/azul-claro.png', 'img/azul-claro.png'] },
        ],
        defaultImgs: ['img/lima.png', 'img/lima-2.png', 'img/lima-3.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20LIMA%20de%20YOSSICO',
    },

    core: {
        id: 'core',
        name: 'CORE',
        line: 'Core',
        sub: 'Set · Top + Pantalón · Tela Técnica',
        price: 229900,
        priceDisplay: '$229.900 COP',
        tag: 'Core',
        desc: 'La línea Core nace para la profesional que da sus primeros pasos con YOSSICO. Confección limpia, corte funcional y tela técnica de alto rendimiento. Sin adornos innecesarios, solo lo esencial llevado con orgullo. Disponible en tres colores icónicos.',
        features: [
            { label: 'Composición', value: 'Tela técnica 100% poliéster de alto desempeño' },
            { label: 'Corte', value: 'Fit estándar · corte funcional unisex adaptado para mujer' },
            { label: 'Detalles top', value: 'Cuello redondo · bolsillos laterales' },
            { label: 'Pantalón', value: 'Bota recta · elástico + cordón en cintura' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina · resistente al desgaste · no usar suavizante' },
        ],
        colors: [
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/core-negro.png', 'img/core-azul.png', 'img/core-morado.png'] },
            { key: 'azul-oscuro', label: 'Azul Marino', hex: '#1a2744', imgs: ['img/core-azul.png', 'img/core-negro.png', 'img/core-morado.png'] },
            { key: 'morado', label: 'Morado Oscuro', hex: '#3b1a5e', imgs: ['img/core-morado.png', 'img/core-negro.png', 'img/core-azul.png'] },
        ],
        defaultImgs: ['img/core-negro.png', 'img/core-azul.png', 'img/core-morado.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20CORE%20de%20YOSSICO',
    },
};
