/* ═══════════════════════════════════════════════
   YOSSICO — Catálogo de Productos
   ═══════════════════════════════════════════════ */

const YOSSICO_PRODUCTS = {

    oslo: {
        id: 'oslo',
        name: 'OSLO',
        line: 'Essentials',
        sub: 'Set · Scrub Femenino · Top + Pantalón',
        price: 275900,
        priceDisplay: '$275.900 COP',
        tag: 'Essentials',
        desc: 'Inspirado en la serenidad escandinava, el Set OSLO combina líneas limpias y una paleta de colores sobria con una confección estructurada. Top con cuello V clásico, bolsillos funcionales a los lados y pantalón recto de corte femenino con elástico y cordón. Pensado para la profesional que valora el confort sin sacrificar la elegancia.',
        features: [
            { label: 'Composición', value: '92% poliéster + 8% spandex' },
            { label: 'Gramaje', value: '170g/m²' },
            { label: 'Corte', value: 'Slim fit femenino · talle entallado' },
            { label: 'Detalles top', value: 'Cuello V con vivo · dos bolsillos laterales · vivo en mangas' },
            { label: 'Pantalón', value: 'Bota recta · elástico + cordón en cintura · bolsillos laterales' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina frío · no usar secadora · plancha a baja temperatura' },
        ],
        colors: [
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/oslo_black_front.png', 'img/oslo_black_half.png', 'img/oslo_black_back.png'] },
            { key: 'azul-oscuro', label: 'Azul Marino', hex: '#1a2744', imgs: ['img/oslo_navy_front.png', 'img/oslo_navy_half.png', 'img/oslo_navy_back.png'] },
            { key: 'vinotinto', label: 'Vinotinto', hex: '#5c2836', imgs: ['img/oslo_burgundy_front.png', 'img/oslo_burgundy_half.png', 'img/oslo_burgundy_back.png'] },
        ],
        defaultImgs: ['img/oslo_black_front.png', 'img/oslo_black_half.png', 'img/oslo_black_back.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20OSLO%20de%20YOSSICO',
    },

    milan: {
        id: 'milan',
        name: 'MILAN',
        line: 'Signature',
        sub: 'Set · Scrub Femenino · Top + Pantalón',
        price: 339900,
        priceDisplay: '$339.900 COP',
        tag: 'Signature',
        desc: 'El Set MILAN captura la elegancia italiana con un top de cuello mao, corte entallado y pantalón recto de alta precisión. En navy profundo, proyecta autoridad y sofisticación en cada turno. La línea Signature eleva el uniforme a una declaración de identidad profesional.',
        features: [
            { label: 'Composición', value: '72% poliéster + 21% rayón + 7% spandex' },
            { label: 'Gramaje', value: '210g/m²' },
            { label: 'Corte', value: 'Slim fit · corte entallado con mayor movilidad' },
            { label: 'Detalles top', value: 'Cuello mao · botones al tono · bolsillo pecho izquierdo con bordado' },
            { label: 'Pantalón', value: 'Bota recta · elástico + cordón · dos bolsillos laterales y uno trasero' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina frío · no usar secadora · plancha a baja temperatura' },
        ],
        colors: [
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/milan_front.png', 'img/milan_detail.png', 'img/milan_back.png'] },
        ],
        defaultImgs: ['img/milan_front.png', 'img/milan_detail.png', 'img/milan_back.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20MILAN%20de%20YOSSICO',
    },

    kyoto: {
        id: 'kyoto',
        name: 'KYOTO',
        line: 'Signature',
        sub: 'Set · Scrub Femenino · Top + Pantalón',
        price: 339900,
        priceDisplay: '$339.900 COP',
        tag: 'Signature',
        desc: 'KYOTO encarna la filosofía zen japonesa: un top cruzado con cuello cruzado y pantalón palazzo de caída impecable. Para la profesional que busca fluidez, calma y presencia. La línea Signature está diseñada para quienes entienden que el detalle lo es todo.',
        features: [
            { label: 'Composición', value: '72% poliéster + 21% rayón + 7% spandex' },
            { label: 'Gramaje', value: '210g/m²' },
            { label: 'Corte', value: 'Palazzo · pantalón ancho de caída fluida' },
            { label: 'Detalles top', value: 'Cuello cruzado · cierre oculto · bolsillos laterales profundos' },
            { label: 'Pantalón', value: 'Palazzo amplio · elástico en cintura · caída premium' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina frío · no usar secadora · plancha a baja temperatura' },
        ],
        colors: [
            { key: 'azul-oscuro', label: 'Azul Marino', hex: '#1a2744', imgs: ['img/kyoto_front.png', 'img/kyoto_detail.png', 'img/kyoto_back.png'] },
        ],
        defaultImgs: ['img/kyoto_front.png', 'img/kyoto_detail.png', 'img/kyoto_back.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20KYOTO%20de%20YOSSICO',
    },

    lima: {
        id: 'lima',
        name: 'LIMA',
        line: 'Essentials',
        sub: 'Set · Scrub Femenino · Top + Pantalón',
        price: 275900,
        priceDisplay: '$275.900 COP',
        tag: 'Essentials',
        desc: 'LIMA captura la calidez latinoamericana en un diseño atemporal. Top suelto con cuello V redondeado y pantalón palazzo de caída fluida, pensado para quienes buscan comodidad sin perder el estilo. Una prenda que acompaña desde el primer turno hasta el último.',
        features: [
            { label: 'Composición', value: '72% poliéster + 22% rayón + 6% spandex' },
            { label: 'Gramaje', value: '166g/m²' },
            { label: 'Corte', value: 'Fit holgado · top suelto con pantalón de caída fluida' },
            { label: 'Detalles top', value: 'Cuello V redondeado · bolsillos laterales · dobladillo recto' },
            { label: 'Pantalón', value: 'Palazzo · elástico en cintura · amplitud total en bota' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina frío · no usar secadora · plancha a baja temperatura' },
        ],
        colors: [
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/lima_black_front.png', 'img/lima_black_half.png', 'img/lima_black_back.png'] },
            { key: 'azul-pacifico', label: 'Azul Pacífico', hex: '#1B6B6B', imgs: ['img/lima_teal_front.png', 'img/lima_teal_half.png', 'img/lima_teal_back.png'] },
            { key: 'verde-oliva', label: 'Verde Oliva', hex: '#7A8C5E', imgs: ['img/lima_olive_front.png', 'img/lima_olive_half.png', 'img/lima_olive_back.png'] },
        ],
        defaultImgs: ['img/lima_black_front.png', 'img/lima_black_half.png', 'img/lima_black_back.png'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20LIMA%20de%20YOSSICO',
    },

    bogota: {
        id: 'bogota',
        name: 'BOGOTÁ',
        line: 'Core',
        sub: 'Set · Top + Pantalón · Tela Técnica',
        price: 229900,
        priceDisplay: '$229.900 COP',
        tag: 'Core',
        desc: 'BOGOTÁ es el primer uniforme de la línea Core. Confección limpia, corte funcional y tela técnica de alto rendimiento para la profesional que da sus primeros pasos con YOSSICO. Sin adornos innecesarios, solo lo esencial llevado con orgullo.',
        features: [
            { label: 'Composición', value: '94% poliéster + 6% spandex' },
            { label: 'Gramaje', value: '120g/m²' },
            { label: 'Corte', value: 'Fit estándar · corte funcional adaptado para mujer' },
            { label: 'Detalles top', value: 'Cuello redondo · bolsillos laterales' },
            { label: 'Pantalón', value: 'Bota recta · elástico + cordón en cintura' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina · resistente al desgaste · no usar suavizante' },
        ],
        colors: [
            { key: 'negro', label: 'Negro', hex: '#111111', imgs: ['img/core-negro.webp', 'img/core-azul.webp', 'img/core-morado.webp'] },
            { key: 'azul-oscuro', label: 'Azul Marino', hex: '#1a2744', imgs: ['img/bogota_navy_front.png', 'img/bogota_navy_half.png', 'img/bogota_navy_back.png'] },
            { key: 'morado', label: 'Morado Violeta', hex: '#3b1a5e', imgs: ['img/core-morado.webp', 'img/core-negro.webp', 'img/core-azul.webp'] },
        ],
        defaultImgs: ['img/core-negro.webp', 'img/bogota_navy_front.png', 'img/core-morado.webp'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20BOGOTÁ%20de%20YOSSICO',
    },

    manta: {
        id: 'manta',
        name: 'MANTA',
        line: 'Core',
        sub: 'Set · Top + Pantalón · Tela Técnica',
        price: 229900,
        priceDisplay: '$229.900 COP',
        tag: 'Core',
        desc: 'MANTA es el segundo uniforme de la línea Core. Un diseño depurado y funcional con corte que prioriza el movimiento. Disponible en Azul Marino, un color que transmite calma y profesionalismo en cada turno.',
        features: [
            { label: 'Composición', value: '94% poliéster + 6% spandex' },
            { label: 'Gramaje', value: '120g/m²' },
            { label: 'Corte', value: 'Fit estándar · corte funcional adaptado para mujer' },
            { label: 'Detalles top', value: 'Cuello redondo · bolsillos funcionales' },
            { label: 'Pantalón', value: 'Bota recta · elástico + cordón en cintura' },
            { label: 'Tallas', value: 'S — M — L' },
            { label: 'Cuidado', value: 'Lavado a máquina · resistente al desgaste · no usar suavizante' },
        ],
        colors: [
            { key: 'azul-oscuro', label: 'Azul Marino', hex: '#1a2744', imgs: ['img/core-azul.webp', 'img/core-azul.webp', 'img/core-azul.webp'] },
        ],
        defaultImgs: ['img/core-azul.webp', 'img/core-azul.webp', 'img/core-azul.webp'],
        wa: 'Hola,%20quiero%20información%20sobre%20el%20Set%20MANTA%20de%20YOSSICO',
    },
};
